/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.start;

import com.crypto.AES;
import com.crypto.RSA;
import com.helper.Global;
import com.helper.Helper;
import com.helper.JSONHelper;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import bwmorg.bouncycastle.util.encoders.Base64;
import com.crypto.AES_net;
import com.helper.Config;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author Abubakar Butt
 */
public class StartApp extends javax.swing.JFrame {

    /**
     * Creates new form StartApp
     */
    public StartApp() {
        initComponents();
        Reg_panel.setVisible(false);
        Login_panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reg_panel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Login_panel = new javax.swing.JPanel();
        loginmailtxt = new javax.swing.JTextField();
        loginpasstxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        Regbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Message_panel = new javax.swing.JPanel();
        messagetxt = new javax.swing.JTextField();
        sndmsgbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jTextField2.setText("jTextField2");

        passwordtxt.setText("jPasswordField1");

        jLabel1.setText("Email");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Registration");

        javax.swing.GroupLayout Reg_panelLayout = new javax.swing.GroupLayout(Reg_panel);
        Reg_panel.setLayout(Reg_panelLayout);
        Reg_panelLayout.setHorizontalGroup(
            Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Reg_panelLayout.createSequentialGroup()
                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Reg_panelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel7))
                    .addGroup(Reg_panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Reg_panelLayout.createSequentialGroup()
                                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        Reg_panelLayout.setVerticalGroup(
            Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Reg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(56, 56, 56)
                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(Reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(Reg_panel, "card2");

        loginpasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpasstxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        jLabel5.setText("Password");

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        Regbtn.setText("Registration");
        Regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Login");

        javax.swing.GroupLayout Login_panelLayout = new javax.swing.GroupLayout(Login_panel);
        Login_panel.setLayout(Login_panelLayout);
        Login_panelLayout.setHorizontalGroup(
            Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_panelLayout.createSequentialGroup()
                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Login_panelLayout.createSequentialGroup()
                                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Regbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Login_panelLayout.createSequentialGroup()
                                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginpasstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(loginmailtxt)))))
                    .addGroup(Login_panelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        Login_panelLayout.setVerticalGroup(
            Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(65, 65, 65)
                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(63, 63, 63)
                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regbtn)
                    .addComponent(loginbtn))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(Login_panel, "card3");

        Message_panel.setPreferredSize(new java.awt.Dimension(501, 407));

        sndmsgbtn.setText("sendmsg");
        sndmsgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndmsgbtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Messages");

        javax.swing.GroupLayout Message_panelLayout = new javax.swing.GroupLayout(Message_panel);
        Message_panel.setLayout(Message_panelLayout);
        Message_panelLayout.setHorizontalGroup(
            Message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Message_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sndmsgbtn)
                .addGap(105, 105, 105))
            .addGroup(Message_panelLayout.createSequentialGroup()
                .addGroup(Message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Message_panelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(messagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Message_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        Message_panelLayout.setVerticalGroup(
            Message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Message_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Message_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addComponent(messagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(sndmsgbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(Message_panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loginpasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpasstxtActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        try {
            String pk = Global.getSERVER_PUBLIC_KEY();
            Global.setSESSION_KEY(AES_net.GenrateKey());
            PublicKey server_pub_key = Helper.importPublicKey(pk);
            String pass1 = new String(loginpasstxt.getPassword());

            String pass = new String(Base64.encode(RSA.encrypt(Helper.hash(pass1), server_pub_key)));

            String url = Config.SERVER + Config.LOGIN + "&email=" + Helper.encodeurl(new String(Base64.encode(RSA.encrypt(loginmailtxt.getText(), server_pub_key)))) + "&pass=" + Helper.encodeurl(pass) + "";
            StringBuffer msg = JSONHelper.GetJsonResponse(url);
            JSONObject jsonObj = new JSONObject(msg.toString());
            String Reply = jsonObj.getString("Response");
            Global.setPRIVATE_KEY(jsonObj.getString("pri_key"));
            Global.setPUBLIC_KEY(jsonObj.getString("pub_key"));

            if (Reply.equalsIgnoreCase("Successfully Login")) {
                Global.setPASS(pass1);
                // System.out.println(Global.getPASS());
           
              String s=Global.getSESSION_KEY();
            pk = new String(Base64.encode(RSA.encrypt(Global.getSESSION_KEY(), server_pub_key)));
            String url2 = Config.SERVER + Config.SEND_SESSION + "&msg=" + Helper.encodeurl(pk) + "&email=" + Helper.encodeurl(new String(Base64.encode(RSA.encrypt(loginmailtxt.getText(), server_pub_key)))) + "";
            // System.out.println(url);

            StringBuffer msg2 = JSONHelper.GetJsonResponse(url2);
            JSONObject jsonObj2 = new JSONObject(msg2.toString());
            pk = jsonObj2.getString("Response");
                if(pk.equalsIgnoreCase("Session Created"))
                    {
                          jLabel8.setText("Secure Session Created..");
                     }
                
            Message_panel.setVisible(true);
             Login_panel.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Some error occur while login");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private void sndmsgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndmsgbtnActionPerformed
        // TODO add your handling code here:
        try {

            String pk = Global.getSERVER_PUBLIC_KEY();
            // System.out.println(pk);
            PublicKey pub_key = Helper.importPublicKey(pk);
            String message=AES_net.encrypt(messagetxt.getText(), Global.getSESSION_KEY());
            
            String url = Config.SERVER + Config.SEND_MESSAGE + "&msg=" + Helper.encodeurl(message) + "&email=" + Helper.encodeurl(new String(Base64.encode(RSA.encrypt(loginmailtxt.getText(), pub_key)))) + "";
            
            StringBuffer msg2 = JSONHelper.GetJsonResponse(url);
            JSONObject jsonObj = new JSONObject(msg2.toString());
            String  pk1 = jsonObj.getString("Response");
            //System.out.println(Global.getPASS());
            String palintext = AES_net.decrypt(pk1, Global.getSESSION_KEY());
            //PrivateKey pub_key2= Helper.importPrivateKey("MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMeLuXV9ZQtWrh6l83iVKObXGRWm9ELgjUvHTx71kgjwa6oEhWFu/JFKSkOeBoJuoSvLuPSbzfdEr1rNslLWoz75TNSxF+AUUl5Fh0NIwl5JNKbRmzL+ew9wVVz9sDnTqaywutdygQneIG2XsoyqSROW5lgeypZzZ8q2/Fis/cUfAgMBAAECgYBounCPtUw+8zNXaomqE77vyJylvIYeQ3Rk/SoNeZ03i9c12EGYrYNpTbBEZL/N3PpB3h4oY01qJWZTJfodeAEcsZwrd57ghoOidcvrsGYZ/UV0i4IY5e54tYdDnQf/NgT6QUMVLEsSjqLaM9IjBf8kK1vgdi77CDKybVVDxU9AAQJBAPl03oNS/N1iTXRK3qaLRPfQWs6QnYCyEDEMVKGVeGk21KMMXYVSZlACVDedzTXkgyEJsxqN6lXjkPRo/Bo+DR8CQQDMx7LeSwi+z5uwHOoI4bpaed4H7xKWpga/3bM2ehwkfE8e0dNzxkzous6SJzblAAMHre91T6CZnlhOBlvAEUgBAkB1VKPoLttioX7+yMxKl0zcJnLfn6OFSbtV5o/T5ILbMf/3pLREJgqbbU0BT8aap52Jp49HWSK0PTIL02loSnFPAkEAv+ASEkWeQSPIDkFZbM8MzL/JsgdplGymgFqcFFxgSDON8yPKDH3vDFYVPk6uGe5j6GsqpvHgWnBK73j3uUS4AQJBAKoJaYiWlhKiGQJ7lPSlzWiXiNI3Sb1fG9DejSd5jq2j71i4pEVWdPT2v1nAqpC2Jf+Fu3zcRSekrPkMSbm9hvM=");
            JOptionPane.showMessageDialog(this, palintext);
        } catch (Exception ne) {

        }

    }//GEN-LAST:event_sndmsgbtnActionPerformed

    private void RegbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegbtnActionPerformed
        // TODO add your handling code here:
        Reg_panel.setVisible(true);
        Login_panel.setVisible(false);
    }//GEN-LAST:event_RegbtnActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        try {

            String pk = Global.getSERVER_PUBLIC_KEY();
            PublicKey sever_pub_key = Helper.importPublicKey(pk);
            String email, unam, pass;

            pass = new String(Base64.encode(RSA.encrypt(Helper.hash(new String(passwordtxt.getPassword())), sever_pub_key)));
            email = new String(Base64.encode(RSA.encrypt(jTextField1.getText(), sever_pub_key)));
            unam = new String(Base64.encode(RSA.encrypt(jTextField2.getText(), sever_pub_key)));
            String url = Config.SERVER + Config.SIGNUP + "&pass=" + Helper.encodeurl(pass) + "&email=" + Helper.encodeurl(email) + "&U_name=" + Helper.encodeurl(unam) + "";
            StringBuffer msg = JSONHelper.GetJsonResponse(url);
            JSONObject jsonObj = new JSONObject(msg.toString());
            String Reply = jsonObj.getString("Response");

            if (Reply.equalsIgnoreCase("Successfully Register")) {

                Global.setPASS(new String(passwordtxt.getPassword()));

                final KeyPair key = RSA.generateKey();

                // System.out.print(new String(key.getPrivate().getEncoded()));
                String User_prik = new String(Base64.encode(key.getPrivate().getEncoded()));
                //System.out.println(User_prik);
                User_prik = AES.encrypt(User_prik, Global.getPASS());
                Global.setPRIVATE_KEY(User_prik);
                // String temp = AES.decrypt(User_prik, pass);

                //Global.setPRIVATE_KEY(User_prik);
                Global.setPUBLIC_KEY(new String(Base64.encode(key.getPublic().getEncoded())));

                url = Config.SERVER + Config.SAVE_USER_KEYS + "&pub_key=" + Helper.encodeurl(Global.getPUBLIC_KEY()) + "&pri_key=" + Helper.encodeurl(User_prik) + "&email=" + Helper.encodeurl(email) + " ";
                StringBuffer msg2 = JSONHelper.GetJsonResponse(url);
                JSONObject jsonObj2 = new JSONObject(msg.toString());
                Reply = jsonObj2.getString("Response");
            }

            JOptionPane.showMessageDialog(this, Reply);

            Reg_panel.setVisible(false);
            Login_panel.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_panel;
    private javax.swing.JPanel Message_panel;
    private javax.swing.JPanel Reg_panel;
    private javax.swing.JButton Regbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField loginmailtxt;
    private javax.swing.JPasswordField loginpasstxt;
    private javax.swing.JTextField messagetxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JButton signup;
    private javax.swing.JButton sndmsgbtn;
    // End of variables declaration//GEN-END:variables
}
